#!/usr/bin/env ruby
require "tbity"
Encoding.default_external = "UTF-8"

begin
  status = Tbity::CLI.start(ARGV)
  exit(true)
rescue => e
  STDERR.puts e.message
  STDERR.puts e.backtrace
  exit(false)
end
